Migration guide draft
diesel-rs/diesel pull request #3120
Opened 2022-04-05 20:16 UTC by weiznich

This PR adds a first draft of the migration guide for the diesel 2.0 release. I would like to have something in place for a rc release.

[Rendered draft](https://github.com/weiznich/diesel/blob/migration_guide/guide_drafts/migration_guide.md)

Additionally I've put two small other related changes in here:
* Updating the changelog a bit
* Moving `assume_not_nullable` to `NullableExpressionMethods` as that is a better place for it, right next to `nullable()`.

Comments and improvements to the guide are welcome.

(To the other changes as well)

2022-04-05 21:35 UTC, czotomo requested changes
Great writeup! Few comments here and there.
Disclaimer: I am not a native English speaker, nor a seasoned Diesel developer so I fully expect some of my suggestions to be overruled.
That said, thanks for writing all of that down!

2022-04-05 21:35 UTC, czotomo commented on CHANGELOG.md
> +* The deprecated bash completions command (`diesel bash-completions`) has been removed.
I am personally guilty of writing this changelog entry but now I think it's redundant given the very first line, which states
"Everything previously deprecated has been removed".

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Diesel 2.0 changes large parts of the internal implementation of diesel.
```suggestion
Diesel 2.0 introduces substantial changes to Diesel's inner workings. 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +are deprecated on Diesel 1.4.x.
```suggestion
are marked as deprecated in Diesel 1.4.x.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +We expect that not all users are effected equally by different required changes.
I am not sure this lines is necessary, especially since the wording of the next one specifically states that "your mileage may vary", basically

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +the following changes:
"The following changes are guaranteed to be affecting all of the users intending to migrate to Diesel 2.0:" ❔

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Any users of `diesel_migration` are additionally affected by the following change:
```suggestion
Users of `diesel_migration` are additionally affected by the following change:
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Any user of `BoxableExpression` might be affected by the following change:
```suggestion
Users of `BoxableExpression` might be affected by the following change:
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Any users that implement support for their SQL types or type mappings are affected
```suggestion
Users that implement support for their SQL types or type mappings are affected 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Any user that used the `no_arg_sql_function!` macro might want to replace their usage:
```suggestion
`no_arg_sql_function!` macro is now pending deprecation.
Users of the macro are advised to consider `sql_function!` macro.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Users that update generic diesel code will also be affected by the following changes:
```suggestion
Users that update generic Diesel code will also be affected by the following changes:
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +We do not provide explicit migration steps there, but we encourage users to reach out for questions there.
```suggestion
We do not provide explicit migration steps but we encourage users to reach out with questions pertaining to these changes. 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +are required for all usages of a `Connection` type:
```suggestion
are required for all usages of the `Connection` type:
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +We expect that this is a straightforward change as there connection already can execute only one query at the time.
```suggestion
We expect this to be a straightforward change as the connection can already execute only one query at a time.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +We have updated all of our diesel derive attributes to follow the patterns that are used
```suggestion
We have updated all of our Diesel derive attributes to follow the patterns that are used
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +widely in the rust ecosystem. This means that all of them need to be wrapped by `#[diesel()]` now. And you can specify multiple attributes on the same line now separated by `,`.
```suggestion
widely in the Rust's ecosystem. This means that all of them need to be wrapped by `#[diesel()]` now.  You can now specify multiple attributes on the same line using `,` separator.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +We have completely rewritten the `diesel_migration` crate. As part of this rewrite all
```suggestion
We have completely rewritten the `diesel_migration` crate. As a part of this rewrite all 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +type and for `HarnessWithOutput`. Checkout their documentation for details.
```suggestion
type and for `HarnessWithOutput`. Refer to their documentations for details.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Additionally this rewrite changed the way we provide migrations. Instead of having a own implementation
```suggestion
Additionally, this rewrite changed the way we provide migrations. Instead of having our own implementation
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +closely the behaviour of the underlying databases. We expect that this change has the biggest impact on existing usages
```suggestion
closely the behaviour of the underlying databases. We expect this change to have the biggest impact on existing usages
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +of `BoxableExpression` as it may change the resulting sql type there. As possibly workaround for divering sql types
```suggestion
of `BoxableExpression` as it may change the resulting sql type there. As a possible workaround for divering sql types 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Additionally the diesel CLI tool was changed so that it automatically generates the rust side definition of custom SQL types
```suggestion
Additionally the diesel CLI tool was changed so that it automatically generates the Rust side definition of custom SQL types 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +We restructured the way diesel serializes rust values to their backend specific representation.
```suggestion
We restructured the way Diesel serializes Rust values to their backend specific representation.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +For backend concrete implementations there are the following functions avaible to workaround this limitation:
```suggestion
For backend concrete implementations, the following functions allow to work around this limitation:
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +* `Output::set_value()` for the `Sqlite` backend (Checkout the documentation of `SqliteBindValue` for accepted values)
```suggestion
* `Output::set_value()` for the `Sqlite` backend (Refer to the documentation of `SqliteBindValue` for accepted values)
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +We changed the raw value representation for both, the postgres and mysql
```suggestion
We changed the raw value representation for both PostgreSQL and MySQL
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +backend, from a `& [u8]` to an opaque type. This allows us to include additional information like the database side
```suggestion
backends, from a `& [u8]` to an opaque type. This allows us to include additional information like the database side
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +type there. This change enables users to write `FromSql` implementations that decide dynamically which kind of value
```suggestion
type there. This change enables users to write `FromSql` implementations that decide dynamically what kind of value
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +affects any usage of `no_arg_sql_function!` in third party crates.
```suggestion
affects all of the usages of the `no_arg_sql_function!` in third party crates.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Diesel does now fully enforce aggregation rules, which required us to change the way we represent aggregation
```suggestion
Diesel now fully enforces the aggregation rules, which required us to change the way we represent the aggregation 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +at the type system level. This is used to provide `group_by` support. Diesels aggregation rules
```suggestion
at the type system level. This is used to provide `group_by` support. Diesel's aggregation rules 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +match the semantics of PostgreSQL or Mysql with the `ONLY_FULL_GROUP_BY` option enabled.
```suggestion
match the semantics of PostgreSQL or MySQL with the `ONLY_FULL_GROUP_BY` option enabled.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +As part of this change we removed the `NonAggregate` trait in favor of a new more expressive `ValidGrouping`
```suggestion
As part of this change we removed the `NonAggregate` trait in favor of a new, more expressive `ValidGrouping`
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +Checkout the documentation of `ValidGrouping` for details there.
```suggestion
Refer to the documentation of `ValidGrouping` for details.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +In addition any occurrence of `NonAggregate` in trait bounds needs to be replaced. Again the following
```suggestion
In addition, any occurrence of `NonAggregate` in trait bounds needs to be replaced. Again, the following
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +In addition to the changes listed above, we changed numerous internal details of diesel. This will have impacts on
```suggestion
In addition to the changes listed above, we changed numerous internal details of Diesel. This will have impact on
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +most people that wrote non trivial generic code abstracting over diesel. This section tries to list as much of those
```suggestion
most codebases that include non-trivial generic code abstracting over Diesel. This section tries to list as much of those
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +have always been private to diesel. This change enforces this distinction a in a stricter way. In addition some
```suggestion
have always been private to Diesel. This change enforces this distinction in stricter way. In addition, some
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +we reserve the right to change these API's between different diesel 2.x minor releases, so you should always specify
```suggestion
we reserve the right to change these APIs between different Diesel 2.x minor releases, so you should always pin
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +a concrete minor release version if you use these API's.
```suggestion
a concrete minor release version if you use these APIs.
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +`Queryable<ST, DB>` is now equivalent to `FromSqlRow<ST, DB>`. The later is used as actual trait bound
```suggestion
`Queryable<ST, DB>` is now equivalent to `FromSqlRow<ST, DB>`. The latter is used as an actual trait bound 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +`QueryableByName<DB>` is now equivalent to `FromSqlRow<Untyped, DB>`. The later is used as actual trait
```suggestion
`QueryableByName<DB>` is now equivalent to `FromSqlRow<Untyped, DB>`. The latter is used as an actual trait 
```

2022-04-05 21:35 UTC, czotomo commented on guide_drafts/migration_guide.md
> +With diesel 2.0 we introduced a way to specialise `QueryFragment` implementations for specific backend, while
```suggestion
With Diesel 2.0, we introduced a way to specialise `QueryFragment` implementations for specific backend, while 
```

2022-04-06 14:18 UTC, weiznich reviewed
Thanks for the suggestions. As you probably noticed I'm not a native speaker myself, so a certain amount of errors always happen 🙈

2022-04-08 20:39 UTC, czotomo approved these changes

2022-04-09 08:41 UTC, merged