Implementing ToSql for [u8;N]
diesel-rs/diesel pull request #3714
Opened 2023-07-25 17:59 UTC by snf

2023-07-25 18:03 UTC, weiznich commented
Thanks for opening this PR. Could you add at least some minor text for the motivation of that PR.

2023-07-26 11:55 UTC, weiznich requested changes
Thanks for the update. The change itself looks good. 

I would like to see a test for that in `diesel_tests/tests/types.rs` just to have something for the future to assert that this impl is there.

2023-07-26 12:37 UTC, weiznich approved these changes
Thanks

2023-07-26 12:39 UTC, snf commented
Thank you! Waiting for the tests though

2023-07-26 12:41 UTC, weiznich commented
> Waiting for the tests though

It's configured in such a way that it only merges the PR if the test passes. I just allows me to not coming back for merging in a day or two if everything is fine.

2023-07-26 12:52 UTC, snf commented
I'll come back to it this afternoon (failed test)

2023-07-26 16:54 UTC, snf commented
I'm not sure all of this is actually needed. I can also squash the commits into a single one to reduce noise.

2023-07-26 18:26 UTC, weiznich approved these changes

2023-07-26 19:01 UTC, merged