Use BigInt for integer primary key in sqlite for diesel-cli
diesel-rs/diesel pull request #3940
Opened 2024-02-19 12:26 UTC by stormshield-kg

Fixes #852.

The `sqlite-integer-primary-key-is-bigint` config parameter is used to modify the generation.
With this option, the [`PRAGMA table_list`](https://www.sqlite.org/pragma.html#pragma_table_list) query is used to get the `WITHOUT ROWID` attribute for a table (available from SQLite 3.37).

2024-02-22 07:08 UTC, weiznich requested changes
Thanks for working on this feature :+1:

I generally like the idea to address the underlying issue, but I strongly suggest not to use a feature flag for this as this makes it:

* harder to discover this feature
* harder to document this feature
* harder to test this feature (another entry in the feature matrix…)

Instead I would suggest making this a config option in the `diesel.toml` file and a CLI flag. This allows to control that feature at runtime.

2024-02-22 07:08 UTC, weiznich commented on diesel_cli/src/infer_schema_internals/sqlite.rs
> +    }
```suggestion
    let res = table_list_results
        .iter()
        .find(|wr_info| wr_info.name == table.sql_name)
        .map(|wr_info| !wr_info.without_row_id)
        .unwrap_or_default();
    Ok(res)
```

looks a bit cleaner.

2024-02-22 07:08 UTC, weiznich commented on diesel_cli/src/migrations/diff_schema.rs
> +            let ty = ColumnType {
Can we have a small comment here explaining that this is necessary to make this equivalent to the `ROWID` column? Maybe even with a link to the sqlite documentation?

2024-02-22 07:08 UTC, weiznich commented on diesel_cli/tests/migration_generate.rs
> +        "schema_i64_pk.rs"
This shouldn't be required if that is a config/cli option

2024-02-23 16:14 UTC, weiznich requested changes
Thanks for the update. This looks now much closer to something that is ready to be merged. I've left a few minor comments. The most critical thing is the loading of the primary keys while checking if the column is an alias for rowid. That needs to be fixed, the other comments are more suggestions.

It would also be great to have an entry in the `Changelog.md` file for this feature.

2024-02-23 16:14 UTC, weiznich commented on diesel_cli/src/infer_schema_internals/sqlite.rs
> +            "Parameter `sqlite_integer_primary_key_is_bigint` needs SQLite 3.37 or above".into(),
```suggestion
            format!("Parameter `sqlite_integer_primary_key_is_bigint` needs SQLite 3.37 or above. Your current SQLite version is {sqlite_version}"),
```

2024-02-27 19:50 UTC, merged

2025-08-16 16:12 UTC, teohhanhui commented
~~Sorry for commenting on a closed PR, but was there a reason why this was turned into a `BigInt` instead of `i64` to match [rowid](https://www.sqlite.org/lang_createtable.html#rowid) in SQLite?~~

**EDIT**: Just realized that this is [`diesel::BigInt`](https://docs.rs/diesel/latest/diesel/sql_types/struct.BigInt.html) - not [`num_bigint::BigInt`](https://docs.rs/num-bigint/latest/num_bigint/struct.BigInt.html). My apologies.