`json_typeof` and `jsonb_typeof` function
diesel-rs/diesel pull request #4250
Opened 2024-09-11 07:02 UTC by anna-ahmed19

Added the `json_typeof` and `jsonb_typeof` functions under [Issue#4216](https://github.com/diesel-rs/diesel/issues/4216)

2024-09-11 12:29 UTC, guissalustiano requested changes
Thanks for opening the PR!

The changes look good, I only would like to see some tests about the null behavior, in past cases, Postgres returns `NULL` when you pass `NULL` to this kind of functions.
If this is case, the function signature is wrong, It should also cover the NULL input return.

To fix that we can use 
```rust
fn json_typeof<E: JsonOrNullableJson + SingleValue + MaybeNullableValue<Text>>(e: E) -> E::Out;
```
The `E: MaybeNulllableValue<Text>` says that the output values has the same nullability as the input value. That means Nullable<Json<T>> evaluates to Nullable<Text> and Json<T> evaluates to Text via the Arr::Out return type

2024-09-11 12:29 UTC, guissalustiano commented on diesel/src/pg/expression/functions.rs
> +    /// #     Ok(())
Could you add a test with None input?
It is something like this:
```
    /// let result = diesel::select(json_typeof::<Nullable<Json>, _>(None::<Value>))
    ///     .get_result::<String>(connection)?;
    ///
    /// assert_eq!(<something>, result);
```

2024-09-11 12:29 UTC, guissalustiano commented on diesel/src/pg/expression/functions.rs
> +    /// assert_eq!("null".to_string(), result);
Could you also add a None test here?

2024-09-12 05:53 UTC, anna-ahmed19 commented
Thank you @guissalustiano for the suggestions. 
I have added `MaybeNullableValue<Text>` and the `None` tests. 
Let me know any further changes.

2024-09-12 11:38 UTC, guissalustiano approved these changes
Thanks!

2024-09-12 13:38 UTC, weiznich commented
Thanks for submitting this PR :heart:

2024-09-12 14:24 UTC, merged