`jsonb_pretty` function
diesel-rs/diesel pull request #4254
Opened 2024-09-11 08:49 UTC by anna-ahmed19

Added th `jsonb_pretty` function under [Issue#4216](https://github.com/diesel-rs/diesel/issues/4216)

2024-09-11 12:34 UTC, guissalustiano requested changes
Thanks for opening the PR!

The changes look good, I only would like to see some tests with NULL input (I explain the reason [in yours other PR](https://github.com/diesel-rs/diesel/pull/4250#pullrequestreview-2296751838).

2024-09-11 12:34 UTC, guissalustiano commented on diesel/src/pg/expression/functions.rs
> +    /// #     Ok(())
Could you add a test case with a None input?

2024-09-12 06:25 UTC, anna-ahmed19 commented
Thank you for the suggestion.
I have added `MaybeNullableValue<Text>` and the `None` test.
Let me know if this is alright now.

2024-09-12 12:29 UTC, guissalustiano approved these changes
Thanks!

2024-09-13 06:34 UTC, merged